# Generated by Django 4.2.1 on 2023-05-22 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measurement',
            name='time_measure',
        ),
    ]
