# Generated by Django 4.2.1 on 2023-05-24 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0002_alter_measurement_sensor'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
